#!/bin/sh

#   Copyright 2020-2021 Andrei Datcu.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

VERSIONTAG=v2.3.2
VER="MacLinuxUtils $VERSIONTAG"

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

echo ""
echo ""
echo "This script will install MacLinuxUtils."
echo "MacLinuxUtils doesn't have any dependencies."
echo "If this script installs anything else other than MacLinuxUtils,it has been"
echo "modified externally.In that case,do not run it,first check it's source"
echo "code!"
echo ""
echo "Total installation size :		1.5MiB"
echo ""
read -r -p ":: Proceed with installation? [Y/n] " input

case $input in
    [yY][eE][sS]|[yY])
	echo "Current path : $SCRIPTPATH"
	echo ""
	echo ":: Installing..."

	echo "(1/2)Moving jar and executables..."
	cp -avr $SCRIPTPATH/mlu.jar /opt/mlu.jar
	cp -avr $SCRIPTPATH/mluexp.jar /opt/mluexp.jar
	cp -avr $SCRIPTPATH/maclinuxutils /bin/maclinuxutils

	echo "(2/2)Making maclinuxutils executable..."
	chmod +x /bin/maclinuxutils
	echo ""
	echo ":: Setup finished successfully!"
	;;
    *)
 	exit 1
 	;;
esac
